### ISSUE TITLE
Can this lib be extended for logitech extreme 3D pro?

### ISSUE THREAD

**Issue by rahuldeo2047** [drewnoakes/joystick#10]
Can this be used: /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.1/1-1.1:1.0/0003:046D:C215.0001/input/input6 
?

**Comment by drewnoakes** [comment]
In general you pass the path to the constructor. Eg:

```c++
Joystick js0("/devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.1/1-1.1:1.0/0003:046D:C215.0001/input/input6");
```

However I haven't tried this with PCI device paths such as this.
