### ISSUE TITLE
Missing axis events

### ISSUE THREAD

**Issue by galdalali** [drewnoakes/joystick#12]
Hey there,

I have a weird issue with the joystick. i'm using an [APEM joystick](https://www.apem.com/us/ipd-launch-90.html) inside my application which is design to run at 25Hz but when I try to sample an axis event from the joystick in that speed sometimes I got a false value of 0 when the stick is in my hand (why is that?!) if I work at 10Hz everything works fine with the joystick.
It's not a general load issue since i'm checking this on a stand alone application.

What could be the problem?

**Comment by drewnoakes** [comment]
@galdalali this sounds like a driver issue and unfortunately I'm not very familiar with joystick drivers. Someone else might be able to help you, but I think you'd be better asking on another forum such as Stack Exchange. I'll close this for now.
