### ISSUE TITLE
/dev/input/js0 file hangs with Beaglebone Black

### ISSUE THREAD

**Issue by Rahul5214** [drewnoakes/joystick#7]
**Platform:** 
_Beaglebone black_
```
root@beaglebone:~# uname -a
Linux beaglebone 3.8.13-bone79 #1 SMP Tue Oct 13 20:44:55 UTC 2015 armv7l GNU/Linux

root@beaglebone:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.9 (wheezy)
Release:	7.9
Codename:	wheezy

```

`js0` file hangs whenever DC motor stalls momentarily (controlled using UART pin) in beaglebone black. It stops updating value in `js0` and had to reboot it every time to be able to use joystick (PS3) again.

**Comment by drewnoakes** [comment]
Do you think this is an issue with this library or with your environment (drivers/hardware)?

Are you setting `blocking` to true?

**Comment by Rahul5214** [comment]
All the hardware including PS3 works well with Arduino so it's not a hardware problem. Linux environment or/and joystick library or driver might be causing this problem.

I didn't get `blocking` part. Do I have to set it true and from where?

**Comment by drewnoakes** [comment]
Constructor (or open) accept boolean `blocking` argument. Setting this to 'false' means your read operations won't block, but also might not return anything if the driver is in a broken state.

**Comment by drewnoakes** [comment]
Closing this as I cannot see anything actionable here.
